spring.application.name=trello-app-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/trello_app
spring.datasource.username=trello_user
spring.datasource.password=trello_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
